# Creating AI without such libraries as Torch or TensorFlow

In [13]:
import numpy as np
from numpy.random import default_rng


tst = default_rng(2).random((5, 6))
print(tst)
tst = np.sum(tst, axis=-1)
print(tst)

[[0.26161213 0.29849114 0.81422574 0.09191594 0.60010053 0.72856053]
 [0.18790107 0.05514663 0.27496937 0.65743301 0.56226566 0.15006226]
 [0.43263079 0.6692973  0.42278467 0.6331844  0.96743595 0.68306482]
 [0.39162483 0.18725257 0.34596067 0.51106597 0.89120941 0.77556394]
 [0.3181466  0.9242169  0.47090989 0.69375884 0.10720731 0.10454356]]
[2.79490601 1.88777801 3.80839794 3.10267739 2.61878309]


In [12]:
sum([0.26161213, 0.29849114, 0.81422574, 0.09191594, 0.60010053, 0.72856053])

2.79490601