# Creating AI without such libraries as Torch or TensorFlow

In [4]:
import numpy as np
from numpy.random import default_rng


tst = default_rng(2).random((5, 6))
print(tst)
tst = np.sum(tst, axis=-1)
print(tst)

[[0.26161213 0.29849114 0.81422574 0.09191594 0.60010053 0.72856053]
 [0.18790107 0.05514663 0.27496937 0.65743301 0.56226566 0.15006226]
 [0.43263079 0.6692973  0.42278467 0.6331844  0.96743595 0.68306482]
 [0.39162483 0.18725257 0.34596067 0.51106597 0.89120941 0.77556394]
 [0.3181466  0.9242169  0.47090989 0.69375884 0.10720731 0.10454356]]
[2.79490601 1.88777801 3.80839794 3.10267739 2.61878309]


In [12]:
sum([0.26161213, 0.29849114, 0.81422574, 0.09191594, 0.60010053, 0.72856053])

2.79490601

In [ ]:
import numpy as np

def _masked_fill(x: np.array):
    

3

In [33]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

# Create mask for strictly lower triangle (k = -1 excludes diagonal)
mask = np.tril(np.ones_like(a, dtype=bool), k=-1).T

# Apply mask
a[mask] = -np.inf

print(a)

[[  1. -inf -inf]
 [  4.   5. -inf]
 [  7.   8.   9.]]


In [28]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

np.tril(np.ones_like(a, dtype=bool)).T

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [ ]:
def isPalindrome(x: int) -> bool:
    if x < 0:
        return False

    reveresed_x = 0
    pos = 0
    copy_x = x
    while True:
        if copy_x == 0:
            break
        
        last_dig = copy_x % 10
        reveresed_x = reveresed_x * 10 + last_dig
        copy_x = copy_x // 10
        pos += 1

    return x == reveresed_x


print(isPalindrome(323))

323
True
